package controllers

const (
	SUCCESS_MESSAGE = "Success"

	FAILURE_MESSAGE = "Failure"

	AWS_VALIDATION_ERROR = "ValidationError"

	CREATE_CHANGE_SET_TYPE = "CREATE"

	POLLING_INTERVAL_IN_SECONDS = 10
)

//var TOTAL_TIME_POLLING_IN_MINUTES float64 = 60
