# permissions to do edit cloudresourcedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudresourcedeployment-editor-role
rules:
- apiGroups:
  - cloudresource.keikoproj.io
  resources:
  - cloudresourcedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudresource.keikoproj.io
  resources:
  - cloudresourcedeployments/status
  verbs:
  - get
  - patch
  - update
